### ISSUE TITLE
 Getting requirements to build wheel did not run successfully.

### ISSUE THREAD

**Issue by rafariva** [arvindrajan92/fastanpr#5]
on windows, in CMD when trying to install

Collecting lmdb (from paddleocr>=2.7.0.3->fastanpr)
  Using cached lmdb-1.4.1.tar.gz (881 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      py-lmdb: Using bundled liblmdb with py-lmdb patches; override with LMDB_FORCE_SYSTEM=1 or LMDB_PURE=1.
      Traceback (most recent call last):
        File "<string>", line 92, in <module>
      ModuleNotFoundError: No module named 'patch_ng'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\rafariva\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\rafariva\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\rafariva\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\rafariva\AppData\Local\Temp\pip-build-env-k6yzy5r8\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\rafariva\AppData\Local\Temp\pip-build-env-k6yzy5r8\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\rafariva\AppData\Local\Temp\pip-build-env-k6yzy5r8\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\rafariva\AppData\Local\Temp\pip-build-env-k6yzy5r8\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 94, in <module>
      Exception: Building py-lmdb from source on Windows requires the "patch-ng" python module.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by arvindrajan92** [comment]
Hi @rafariva, could you please share with me the Python version you are using.

**Comment by arvindrajan92** [comment]
@rafariva Try again with Python 3.8-3.10 for Windows. Let me know how you go. Thanks 

Related issue: https://github.com/PaddlePaddle/PaddleOCR/issues/11516

**Comment by Suvoo** [comment]
> on windows, in CMD when trying to install
> 
> Collecting lmdb (from paddleocr>=2.7.0.3->fastanpr) Using cached lmdb-1.4.1.tar.gz (881 kB) Installing build dependencies ... done Getting requirements to build wheel ... error error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [27 lines of output] py-lmdb: Using bundled liblmdb with py-lmdb patches; override with LMDB_FORCE_SYSTEM=1 or LMDB_PURE=1. Traceback (most recent call last): File "", line 92, in ModuleNotFoundError: No module named 'patch_ng'
> 
> ```
>   During handling of the above exception, another exception occurred:
> 
>   Traceback (most recent call last):
>     File "C:\Users\rafariva\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
>       main()
>     File "C:\Users\rafariva\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
>       json_out['return_val'] = hook(**hook_input['kwargs'])
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     File "C:\Users\rafariva\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
>       return hook(config_settings)
>              ^^^^^^^^^^^^^^^^^^^^^
>     File "C:\Users\rafariva\AppData\Local\Temp\pip-build-env-k6yzy5r8\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
>       return self._get_build_requires(config_settings, requirements=['wheel'])
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     File "C:\Users\rafariva\AppData\Local\Temp\pip-build-env-k6yzy5r8\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
>       self.run_setup()
>     File "C:\Users\rafariva\AppData\Local\Temp\pip-build-env-k6yzy5r8\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
>       super().run_setup(setup_script=setup_script)
>     File "C:\Users\rafariva\AppData\Local\Temp\pip-build-env-k6yzy5r8\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
>       exec(code, locals())
>     File "<string>", line 94, in <module>
>   Exception: Building py-lmdb from source on Windows requires the "patch-ng" python module.
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

For Python 3.12 version, use the workaround in this issue - https://github.com/jnwatson/py-lmdb/pull/352. This works well
